SMS/src/java/entities/Poruke.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Grupa2
 */
@Entity
@Table(name = "poruke")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Poruke.findAll", query = "SELECT p FROM Poruke p")
    , @NamedQuery(name = "Poruke.findById", query = "SELECT p FROM Poruke p WHERE p.id = :id")
    , @NamedQuery(name = "Poruke.findByTekst", query = "SELECT p FROM Poruke p WHERE p.tekst = :tekst")})
public class Poruke implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "tekst")
    private String tekst;
    @JoinColumn(name = "roditelji_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Roditelji roditeljiId;
    @JoinColumn(name = "ucitelji_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Ucitelji uciteljiId;

    public Poruke() {
    }

    public Poruke(Integer id) {
        this.id = id;
    }

    public Poruke(Integer id, String tekst) {
        this.id = id;
        this.tekst = tekst;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTekst() {
        return tekst;
    }

    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    public Roditelji getRoditeljiId() {
        return roditeljiId;
    }

    public void setRoditeljiId(Roditelji roditeljiId) {
        this.roditeljiId = roditeljiId;
    }

    public Ucitelji getUciteljiId() {
        return uciteljiId;
    }

    public void setUciteljiId(Ucitelji uciteljiId) {
        this.uciteljiId = uciteljiId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Poruke)) {
            return false;
        }
        Poruke other = (Poruke) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Poruke[ id=" + id + " ]";
    }
    
}

SMS/src/java/entities/Ucitelji.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Grupa2
 */
@Entity
@Table(name = "ucitelji")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Ucitelji.findAll", query = "SELECT u FROM Ucitelji u")
    , @NamedQuery(name = "Ucitelji.findById", query = "SELECT u FROM Ucitelji u WHERE u.id = :id")
    , @NamedQuery(name = "Ucitelji.findByIme", query = "SELECT u FROM Ucitelji u WHERE u.ime = :ime")
    , @NamedQuery(name = "Ucitelji.findByPrezime", query = "SELECT u FROM Ucitelji u WHERE u.prezime = :prezime")
    , @NamedQuery(name = "Ucitelji.findByKorisniciId", query = "SELECT u FROM Ucitelji u WHERE u.korisniciId = :id")})
public class Ucitelji implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "ime")
    private String ime;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "prezime")
    private String prezime;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "uciteljiId")
    private List<Odeljenja> odeljenjaList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "uciteljiId")
    private List<Poruke> porukeList;
    @JoinColumn(name = "korisnici_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Korisnici korisniciId;

    public Ucitelji() {
    }

    public Ucitelji(Integer id) {
        this.id = id;
    }

    public Ucitelji(Integer id, String ime, String prezime) {
        this.id = id;
        this.ime = ime;
        this.prezime = prezime;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIme() {
        return ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

    public String getPrezime() {
        return prezime;
    }

    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    @XmlTransient
    public List<Odeljenja> getOdeljenjaList() {
        return odeljenjaList;
    }

    public void setOdeljenjaList(List<Odeljenja> odeljenjaList) {
        this.odeljenjaList = odeljenjaList;
    }

    @XmlTransient
    public List<Poruke> getPorukeList() {
        return porukeList;
    }

    public void setPorukeList(List<Poruke> porukeList) {
        this.porukeList = porukeList;
    }

    public Korisnici getKorisniciId() {
        return korisniciId;
    }

    public void setKorisniciId(Korisnici korisniciId) {
        this.korisniciId = korisniciId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Ucitelji)) {
            return false;
        }
        Ucitelji other = (Ucitelji) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Ucitelji[ id=" + id + " ]";
    }
    
}

SMS/src/java/managedBeans/OceneManagedBean.java
package managedBeans;

import business.sessionBeans.OceneSessionBeanLocal;
import entities.Ocene;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.inject.Named;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "oceneMB", eager = true)
@SessionScoped
public class OceneManagedBean implements Serializable{

    @EJB
    private OceneSessionBeanLocal oceneBean;   
    private Integer ucenik;
    private int odeljenje;
    private int predmet;
    
    public List<Ocene> getOceneUcenika(){
        setUcenik(1);
        return oceneBean.getOceneUcenika(getUcenik());
    }
    public Integer getUcenik() {
        return ucenik;
    }

    public void setUcenik(Integer ucenik) {
        this.ucenik = ucenik;
    }
    
       public List<Ocene> getAllOcenePoPredmetuOdeljenju() {
        
        return oceneBean.getOceneUcenikaPoPredmetuOdeljenju(3, 2);
    }
       
    public List<Ocene> getAllOcenePoPredmetu() {
        
        return oceneBean.getOceneUcenikaPoPredmetu(3);
    }
    
    public double getProsekPoPredmetuOdeljenju()
    {
        int brojOcena=0;
        int zbirOcena=0;
        double prosek;
        
        List<Ocene> ocene = oceneBean.getOceneUcenikaPoPredmetuOdeljenju(3, 2);
        
        for(Ocene o:ocene)
        {
            zbirOcena+=o.getOcena();
            brojOcena++;
        }
        
        prosek = (double)zbirOcena/brojOcena;
        
        return prosek;                  
        }
    
    public double getProsekPoPredmetu()
    {
        int brojOcena=0;
        int zbirOcena=0;
        double prosek;
        
        List<Ocene> ocene = oceneBean.getOceneUcenikaPoPredmetu(3);
        
        for(Ocene o:ocene)
        {
            zbirOcena+=o.getOcena();
            brojOcena++;
        }
        
        prosek = (double)zbirOcena/brojOcena;
        
        return prosek;                  
        }
}

SMS/src/java/managedBeans/ParentManagedBean.java
package managedBeans;

import business.sessionBeans.ParentSessionBeanLocal;
import entities.Roditelji;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "parentsMB", eager = true)
@SessionScoped
public class ParentManagedBean implements Serializable{
    
    @EJB
    private ParentSessionBeanLocal parentsBean;

    public List<Roditelji> getAllParents() {
        
        return parentsBean.getAllParents();        
    }
}

SMS/src/java/managedBeans/PredmetiManagedBean.java
package managedBeans;

import business.sessionBeans.PredmetiSessionBeanLocal;
import entities.Predmeti;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.html.HtmlDataTable;

@ManagedBean(name ="predmetiMB")
@SessionScoped
public class PredmetiManagedBean implements Serializable{
    
    private String naziv;
    private Predmeti predmet;
    private HtmlDataTable tabelaPredmeti;
    
    private String dodavanjePoruka;
    private String brisanjePoruka;
    
    @EJB
    private PredmetiSessionBeanLocal predmetiBean;
            
    public List<Predmeti> getPredmeti() {
        return predmetiBean.getAllPredmeti();
    } 
    
    public void brisanjePredmeta() {
        predmet = (Predmeti) tabelaPredmeti.getRowData();
        
        if(predmetiBean.brisiPredmet(predmet.getId())) {
            brisanjePoruka = "Predmet uspešno obrisan!";
        }
        else {
           brisanjePoruka = "Greška prilikom brisnja predmeta!";
       }
        System.out.println(predmet.getId());
    }
    
    public void dodavanjePredmeta() {
        
       if(predmetiBean.dodajPredmet(naziv)!=true) {
           dodavanjePoruka = "Predmet verovatno već postoji u bazi!";
       }
       else {
           dodavanjePoruka = "Uspešno dodat predmet!";
       }
    }

    public HtmlDataTable getTabelaPredmeti() {
        return tabelaPredmeti;
    }

    public void setTabelaPredmeti(HtmlDataTable tabelaPredmeti) {
        this.tabelaPredmeti = tabelaPredmeti;
    }

    public Predmeti getPredmet() {
        return predmet;
    }

    public void setPredmet(Predmeti predmet) {
        this.predmet = predmet;
    }

    
    public String getNaziv() {
        return naziv;
    }

    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    public String getDodavanjePoruka() {
        return dodavanjePoruka;
    }

    public void setDodavanjePoruka(String dodavanjePoruka) {
        this.dodavanjePoruka = dodavanjePoruka;
    }

    public String getBrisanjePoruka() {
        return brisanjePoruka;
    }

    public void setBrisanjePoruka(String brisanjePoruka) {
        this.brisanjePoruka = brisanjePoruka;
    }
 
}

SMS/src/java/managedBeans/StudentManagedBean.java
package managedBeans;

import business.sessionBeans.DepartmentSessionBeanLocal;
import business.sessionBeans.StudentSessionBeanLocal;
import business.sessionBeans.UciteljiSessionBeanLocal;
import entities.Ucenici;
import entities.Ucitelji;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "studentMB", eager = true)
@SessionScoped
public class StudentManagedBean implements Serializable{
    
    private Integer odeljenje = null;
    private Integer ucenik = null;
    
    @EJB
    private StudentSessionBeanLocal studentBean;
    @EJB
    private DepartmentSessionBeanLocal departmentBean;
    @EJB
    private UciteljiSessionBeanLocal uciteljiBean;
    
//    @ManagedBean(value = "#{loginMB}")
//    private LoginManagedBean loginMB;
    FacesContext facesContext = FacesContext.getCurrentInstance();
    LoginManagedBean loginMB = (LoginManagedBean)facesContext.getApplication()
      .createValueBinding("#{loginMB}").getValue(facesContext);
    
    public List<Ucenici> getAllStudents() {
        
        return studentBean.getAllStudents();
    }
        public List<Ucenici> getAllStudentsFromDepartment() {
        Ucitelji ucitelji = uciteljiBean.getUciteljByKorisniciId(loginMB.getLoggedInUser().getId());
        setOdeljenje(departmentBean.getDepartmentWhereUciteljiId(ucitelji.getId()).getId());
        return studentBean.getStudentsFromDepartment(getOdeljenje());
    }

    /**
     * @return the odeljenje
     */
    public Integer getOdeljenje() {
        return odeljenje;
    }

    /**
     * @param odeljenje the odeljenje to set
     */
    public void setOdeljenje(Integer odeljenje) {
        this.odeljenje = odeljenje;
    }

    /**
     * @return the ucenik
     */
    public Integer getUcenik() {
        return ucenik;
    }

    /**
     * @param ucenik the ucenik to set
     */
    public void setUcenik(Integer ucenik) {
        this.ucenik = ucenik;
    }
}

SMS/web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Lista ucenika:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "uceniciId" value="#{studentMB.allStudents}" var="ucenici">
                <h:column>
                    <f:facet name="header">Učenik</f:facet>
                        #{ucenici.ime} #{ucenici.prezime}
                </h:column>
                <h:column>    
                    <f:facet name="header">Odeljenje</f:facet>
                        #{ucenici.odeljenjaId.ime}
                </h:column>
                <h:column>   
                    <f:facet name="header">Roditelj</f:facet>
                        #{ucenici.roditeljiId.ime} #{ucenici.roditeljiId.prezime}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        
        <h2>Lista roditelja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id = "roditeljiId" value="#{parentsMB.allParents}" var="roditelji">
                <h:column>
                    <f:facet name="header">Roditelj</f:facet>
                        #{roditelji.ime} #{roditelji.prezime}
                </h:column>
                <h:column>    
                    <f:facet name="header">Nalog</f:facet>
                        #{roditelji.korisniciId.nalog}
                </h:column>
                <h:column>   
                    <f:facet name="header">Loznka</f:facet>
                       #{roditelji.korisniciId.lozinka}
                </h:column>
            </h:dataTable>
        </h:form>
        <br/>
        <h:form>
            <h:link value="Prijava" outcome="index"/>
        </h:form>
    </h:body>
</html>

SMS/web/adminPredmeti.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Predmeti</title>
    </h:head>
    <h:body>
        <h:form id="dodajPredmet">
            <h2><h:outputLabel value="UPRAVLJANJE PREDMETIMA"/></h2><hr/><br/>
            <h:outputLabel style="font-style: italic" value="Dodavanje novog predmeta:"/><br/>
            <h:inputText id="naziv" p:placeholder="Naziv predmeta" autocomplete="false" value="#{predmetiMB.naziv}"/><br/>
            <h:outputLabel value="#{predmetiMB.dodavanjePoruka}" style="color: red"/><br/>
            <h:commandButton value="DODAJ" action="#{predmetiMB.dodavanjePredmeta()}"/>
        </h:form><br/>
        <h:form id="listaPredmeta">
            <h:dataTable binding="#{predmetiMB.tabelaPredmeti}" value="#{predmetiMB.predmeti}" var="pr" border="1">
                <h:column>
                    <f:facet name="header">Naziv</f:facet>
                        #{pr.ime}
                </h:column>
                <h:column>
                    <f:facet name="header">Brisi</f:facet>
                    <h:commandButton value="Obrisi" action="#{predmetiMB.brisanjePredmeta()}">
                        <f:setPropertyActionListener target="#{predmetiMB.predmet}" value="#{pr}" />
                    </h:commandButton>
                </h:column>
            </h:dataTable>
            <h:outputLabel value="#{predmetiMB.brisanjePoruka}" style="color: red"/>
        </h:form>  
    </h:body>
</html>

SMS/web/director.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Lista odeljenja:</h2>
        <hr/>
        <h:form>
            <h:dataTable id= "odeljenjaId" value= "#{directorMB.departments}" var= "odeljenje">
                <h:column>
                    <f:facet name="header">Učitelj</f:facet>
                        #{odeljenje.uciteljiId.ime} #{odeljenje.uciteljiId.prezime}
                </h:column>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{odeljenje.ime}
                </h:column>
                <h:column>
                    <f:facet name="header">Izmena</f:facet>
                    <h:commandButton value='Izmeni'/>
                </h:column>
            </h:dataTable>
        </h:form>
        <h:form>
            <h2>Lista ocena iz #{ocenee.predmetiId.ime} :</h2>
            <h:dataTable id= "oceneTabela" value= "#{oceneMB.allOcenePoPredmetuOdeljenju}" var= "ocenee">            
            <hr/>
                <h:column>
                    <f:facet name="header">Odeljenje</f:facet> 
                        #{ocenee.uceniciId.odeljenjaId.ime}
                </h:column>
                <h:column>
                    <f:facet name="header">Ucenik</f:facet> 
                        #{ocenee.uceniciId.ime} #{ocenee.uceniciId.prezime}  
                </h:column>
                <h:column>
                    <f:facet name="header">Predmet</f:facet>
                        #{ocenee.predmetiId.ime} 
                </h:column>
                <h:column>
                    <f:facet name="header">Ocene</f:facet>
                        #{ocenee.ocena}
                </h:column>              
            </h:dataTable>
        </h:form>
        
        <h:form>
            <h2>Lista ocena po predmetu:</h2>
            <h:dataTable id= "oceneTabela" value= "#{oceneMB.allOcenePoPredmetu}" var= "ocenee">            
            <hr/>
                <h:column>
                    <f:facet name="header">Predmet</f:facet>
                        #{ocenee.predmetiId.ime} 
                </h:column>
                <h:column>
                    <f:facet name="header">Ocene</f:facet>
                        #{ocenee.ocena} 
                </h:column>              
            </h:dataTable>
        </h:form>
            <h:form>
            <h2>Prosek:</h2>
            <h:dataTable id= "oceneTabela" value= "#{oceneMB.prosekPoPredmetuOdeljenju}" var=" ocenee">            
            <hr/>
                <h:column> 
                    <f:facet name="header">Po predmetu i odeljenju</f:facet>
                        #{oceneMB.prosekPoPredmetuOdeljenju} 
                </h:column>        
            </h:dataTable>
        </h:form>
        <h:form>
            <h2>Prosek:</h2>
            <h:dataTable id= "oceneTabela" value= "#{oceneMB.prosekPoPredmetu}" var="o">            
            <hr/>
                <h:column> 
                    <f:facet name="header">Po predmetu</f:facet>
                        #{oceneMB.prosekPoPredmetu} 
                </h:column>        
            </h:dataTable>
        </h:form>
    </h:body>
</html>

SMS/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Elektronski dnevnik - Registracija</title>
        <h:outputStylesheet library="css" name="register.css"/>
    </h:head>
    <h:body>
        <div class="kor">
            <h2>Registracija korisnika:</h2>
            <hr/>
        <h:form class="formaK">
            <h:panelGrid id = "registracijaId" columns = "3" cellpadding = "10" cellspacing = "1">
                <h:outputLabel value = "Ime:" />
                <h:inputText id="ime" required="true" p:placeholder="Ime" requiredMessage="Polje je obavezno!" value="#{registerMB.name}" />
                <h:message for="ime" />
                
                <h:outputLabel value = "Prezime:" />
                <h:inputText id="prezime" required="true" p:placeholder="Prezime" requiredMessage="Polje je obavezno!" value="#{registerMB.surname}" />                                                                                                                                
                <h:message for="prezime" />
                
                <h:outputLabel value = "Nalog:" />
                <h:inputText id="nalog" required="true" p:placeholder="Nalog" requiredMessage="Polje je obavezno!" value="#{registerMB.username}" />
                <h:message for="nalog" />
                
                <h:outputLabel value = "Lozinka:" />
                <h:inputSecret id="lozinka" required="true" p:placeholder="Lozinka" requiredMessage="Polje je obavezno!" value="#{registerMB.password}" />
                <h:message for="lozinka" />
            </h:panelGrid>
 
            <h:panelGrid id = "user" columns = "5" cellpadding = "10" cellspacing = "1">
                <h:selectOneRadio id="radio" required="true" requiredMessage="Obavezno izabrati korisnika!" value="#{registerMB.user}">
                    <f:selectItem itemLabel="Admin" itemValue="0"/>
                    <f:selectItem itemLabel="Direktor" itemValue="1"/>
                    <f:selectItem itemLabel="Učitelj" itemValue="2"/>
                    <f:selectItem itemLabel="Roditelj" itemValue="3"/>
                </h:selectOneRadio>
                <h:message for="radio" />
            </h:panelGrid>
            
                <div name="footerRegister">
                    <h:panelGrid>
                        <f:facet name="footer">
                            <h:commandButton id="registrujSe" value="REGISTRUJ KORISNIKA" action="#{registerMB.registerKorisnika()}" />
                        </f:facet>
                    </h:panelGrid>
                </div>
            <h:outputLabel value="#{registerMB.messageU}" style="color: red"/>
        </h:form>
        </div>
        <div class="kor">
        <h2>Registracija učenika:</h2>
        <hr/>
        <h:form class="formU">
            <h:dataTable id= "registracija" value="#{registerMB}" var="reg">
                <h:column>
                    <f:facet name="header">Ime</f:facet>
                    <h:inputText id="ime" required="true" p:placeholder="Ime" requiredMessage="Polje je obavezno!" value="#{registerMB.name}" /> 
                    <br/><h:message for="ime"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Prezime</f:facet>
                    <h:inputText id="prezime" required="true" p:placeholder="Prezime" requiredMessage="Polje je obavezno!" value="#{registerMB.surname}" /> 
                    <br/><h:message for="prezime"/>
                </h:column>             
            </h:dataTable>
            
            <h3><h:outputLabel value="Izaberite roditelja: "/></h3>
            <h:panelGrid id = "roditelj" cellpadding = "10" cellspacing = "1">
                <h:selectOneRadio id="radioR" required="true" requiredMessage="Neophodno je odabrati roditelja!" value="#{registerMB.parent}">
                    <f:selectItems value="#{parentsMB.allParents}" var="p" itemLabel="#{p.ime} #{p.prezime}" itemValue="#{p.id}"/>
                </h:selectOneRadio>
            </h:panelGrid>
            
            <h3><h:outputLabel value="Izaberite odeljenje:"/></h3>
                <h:panelGrid id = "odeljenje" cellpadding = "10" cellspacing = "1">
                    <h:selectOneRadio id="radioO" required="true" requiredMessage="Neophodno je odabrati odeljenje!" value="#{registerMB.department}">
                        <f:selectItems value="#{departmentMB.departments}" var="o" itemLabel="#{o.ime}" itemValue="#{o.id}"/>
                    </h:selectOneRadio>
                </h:panelGrid>
            <h:outputLabel value="#{registerMB.messageS}" style="color: red"/><br/>
            <h:commandButton value="REGISTRUJ UČENIKA" action="#{registerMB.registerUcenika()}"/>
        </h:form>
        </div>
    </h:body>
</html>